version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin123
      - JWT_SECRET=mysecretkey
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    restart: always
