version: "3.8"
services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin123
      - JWT_SECRET=mysecretkey
      - MEDICINES_FILE=/app/medicines.json
      - REACT_APP_API_URL=/api
    volumes:
      - ./backend/data:/app/data
      - ./backend/medicines.json:/app/medicines.json:ro
    restart: always
