version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin123
      - JWT_SECRET=mysecretkey
      - MEDICINES_FILE=/app/medicines.json
    volumes:
      - ./backend/data:/app/data
      - ./backend/medicines.json:/app/medicines.json:ro
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    restart: always
